@echo off
rem IBM PCMCIA Audio Adapter (no DMA, no FM) - enable with IBMAUDGO first, no IRQ
C:\VSBPCM\JEMM386.EXE LOAD NOEMS X=DC00-DFFF
C:\VSBPCM\IBMAUDGO.COM /W=DC00
cd \VSBPCM
set BLASTER=A220 I7 D1 T4
set SBEPTLAT=80
JLOAD QPIEMU.DLL
HDPMI32I -r -x -v
VSBPCM /CARD:IBMAUD /FMSHIM /A220 %1 %2 %3 %4 %5
cd \
