@echo off
rem IBM PCMCIA Audio Adapter + software OPL3 (FPU needed) - enable with IBMAUDGO first
C:\VSBPCM\JEMM386.EXE LOAD NOEMS X=DC00-DFFF
C:\VSBPCM\IBMAUDGO.COM /W=DC00
cd \VSBPCM
set BLASTER=A220 I7 D1 T4
set SBEPTLAT=160
JLOAD QPIEMU.DLL
HDPMI32I -r -x -v
VSBPCMT /CARD:IBMAUD /RESAMP /A220 %1 %2 %3 %4 %5
cd \
